export default {
  title: 'Civiliation Played',
  name: 'civilization',
  type: 'string',
  options: {
    list: [
      { title: 'Aztecs', value: 'aztecs' },
      { title: 'Berbers', value: 'berbers' },
      { title: 'Britons', value: 'britons' },
      { title: 'Bulgarians', value: 'bulgarians' },
      { title: 'Burmese', value: 'burmese' },
      { title: 'Byzantines', value: 'byzantines' },
      { title: 'Celts', value: 'celts' },
      { title: 'Chinese', value: 'chinese' },
      { title: 'Cumans', value: 'cumans' },
      { title: 'Ethiopians', value: 'ethiopians' },
      { title: 'Franks', value: 'franks' },
      { title: 'Goths', value: 'goths' },
      { title: 'Huns', value: 'huns' },
      { title: 'Incas', value: 'incas' },
      { title: 'Indians', value: 'indians' },
      { title: 'Italians', value: 'italians' },
      { title: 'Japanese', value: 'japanese' },
      { title: 'Khmer', value: 'khmer' },
      { title: 'Koreans', value: 'koreans' },
      { title: 'Lithuanians', value: 'lithuanians' },
      { title: 'Magyars', value: 'magyars' },
      { title: 'Malay', value: 'malay' },
      { title: 'Mayans', value: 'mayans' },
      { title: 'Mongols', value: 'mongols' },
      { title: 'Persians', value: 'persians' },
      { title: 'Portuguese', value: 'portguese' },
      { title: 'Saracens', value: 'saracens' },
      { title: 'Slavs', value: 'slavs' },
      { title: 'Spanish', value: 'spanish' },
      { title: 'Tatars', value: 'tatars' },
      { title: 'Teutons', value: 'teutons' },
      { title: 'Turks', value: 'turks' },
      { title: 'Vietnamese', value: 'vietnamese' },
      { title: 'Vikings', value: 'vikings' },
    ],
  },
};
